// <auto-generated />
namespace AspNetMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _0223 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_0223));
        
        string IMigrationMetadata.Id
        {
            get { return "202102231157040_0223"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
