// <auto-generated />
namespace AspNetMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class delete_membermd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delete_membermd));
        
        string IMigrationMetadata.Id
        {
            get { return "202103120648166_delete_membermd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
