// <auto-generated />
namespace AspNetMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class customerserviceinit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(customerserviceinit));
        
        string IMigrationMetadata.Id
        {
            get { return "202102070556551_customer-service-init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
